// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationService.Context;

#nullable disable

namespace ReservationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250520134758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ReservationService.Models.CustomerInput", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WaitlistTableId")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.HasIndex("WaitlistTableId");

                    b.ToTable("CustomerInput");
                });

            modelBuilder.Entity("ReservationService.Models.CustomerModel", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = "C101",
                            Email = "john.doe@example.com",
                            Name = "Jone Doe"
                        },
                        new
                        {
                            CustomerId = "C102",
                            Email = "jane.smith@example.com",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            CustomerId = "C103",
                            Email = "sam.wilson@example.com",
                            Name = "Sam Wilson"
                        },
                        new
                        {
                            CustomerId = "C104",
                            Email = "emily.davis@example.com",
                            Name = "Emily Davis"
                        });
                });

            modelBuilder.Entity("ReservationService.Models.Waitlist", b =>
                {
                    b.Property<string>("TableId")
                        .HasColumnType("TEXT");

                    b.HasKey("TableId");

                    b.ToTable("Waitlist");
                });

            modelBuilder.Entity("ReservationService.Models.CustomerInput", b =>
                {
                    b.HasOne("ReservationService.Models.Waitlist", null)
                        .WithMany("CustomerQueue")
                        .HasForeignKey("WaitlistTableId");
                });

            modelBuilder.Entity("ReservationService.Models.Waitlist", b =>
                {
                    b.Navigation("CustomerQueue");
                });
#pragma warning restore 612, 618
        }
    }
}
